### ISSUE TITLE
Can't extract in a shared folder

### ISSUE THREAD

**Issue by Doc-Saintly** [PaulLereverend/NextcloudExtract#30]
The path it builds for extracting a file in a shared folder is incorrect, so it fails to extract.

The workaround is to move it back to my own folder, extract, then move the extracted files back to the shared folder.

**Comment by Glujaz** [comment]
Confirm, have the same issue...
But for group folders.

**Comment by ggasconn** [comment]
Same issue here. Happening on Group Folders. 
The error says it cannot open the file. To reproduce just install the group folder app and try to extract any kind of compressed file inside any of the group folders.
![Captura de pantalla 2019-08-18 a las 13 53 39](https://user-images.githubusercontent.com/43778510/63224115-dbad6900-c1bf-11e9-8b85-edafa7602f57.png)

Hope it can get fixed soon! :)

**Comment by PaulLereverend** [comment]
Thank you for the feedback. Will be working on this asap.

**Comment by lmamane** [comment]
Reproduced on version 1.2.2 with NextCloud 17.0.1

**Comment by PaulLereverend** [comment]
@lmamane Shared folders should be working since the last update. 
Otherwise, group folder app is not yet supported.

**Comment by javaminister** [comment]
in user owned folders the APP works. Thank you very mu
![error-extracting-zip](https://user-images.githubusercontent.com/22104685/83762796-35f8b700-a678-11ea-9cb7-cada5de8c612.png)
ch!
The issue about extracting zip-archive in shared folders still exists. 
ubuntu-18.04 with  ownCloud 10.4.1 (stable) and extract-1.2.4 installed.

**Comment by Bolli84** [comment]
Just tried it and is it still not possible in "group_folder".

**Comment by PaulLereverend** [comment]
Group folders are now supported in the latest update (1.3.0).
